services:
  db:
    env_file:
      - backend/.env
    image: postgres:16
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    env_file:
      - backend/.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: db
      RUST_LOG: debug
      ENV RUST_BACKTRACE: "1"
      ENV RUST_STDOUT_LINE_BUFFERED: "1"
    depends_on:
      - db
    volumes:
      - ./backend:/app/backend
    command: ./karaoke

volumes:
  db_data:
